import pandas as pd
import logging
from etl.exceptions import DataLoadError

class Transformer:
    def __init__(self):
        pass

    def transformar(self, df: pd.DataFrame) -> pd.DataFrame:
        try:
            logging.info("üßº Iniciando transforma√ß√µes no DataFrame")

            # Remover duplicatas
            df = df.drop_duplicates()

            # Preencher e padronizar emails
            df["email"] = df["email"].fillna("sem_email@dominio.com").str.lower()

            # Garantir que idade seja num√©rica e v√°lida
            df["idade"] = pd.to_numeric(df["idade"], errors="coerce")
            df = df[df["idade"].between(18, 100)]

            # Remover espa√ßos dos nomes
            df["nome"] = df["nome"].str.strip()

            # Substituir senhas vazias
            df["senha"] = df["senha"].replace("", "123456")

            # Score padr√£o se ausente
            df["score"] = pd.to_numeric(df["score"], errors="coerce").fillna(0.5)

            logging.info("‚úÖ Transforma√ß√µes conclu√≠das")
            return df

        except Exception as e:
            logging.error(f"Erro ao transformar dados: {str(e)}")
            raise DataLoadError("Erro na transforma√ß√£o dos dados") from e
