import os
import pandas as pd
import logging
from etl.exceptions import ETLError

class ValidadorClientes:
    def validar(self, caminho_arquivo: str):
        logging.info(f"üîç Validando o arquivo: {caminho_arquivo}")
        try:
            df = pd.read_csv(caminho_arquivo)
        except Exception as e:
            raise ETLError(f"Erro ao ler CSV: {e}")

        # Verifica colunas obrigat√≥rias
        colunas_necessarias = ["id", "email", "idade"]
        for coluna in colunas_necessarias:
            if coluna not in df.columns:
                raise ETLError(f"Coluna obrigat√≥ria ausente: {coluna}")

        # Verifica se email est√° nulo
        if df["email"].isnull().any():
            raise ETLError("‚ùå Existem emails nulos no dataset.")

        # Verifica idade
        if not df["idade"].between(18, 100).all():
            raise ETLError("‚ùå Existem idades fora do intervalo permitido (18 a 100).")

        logging.info("‚úÖ Valida√ß√£o manual conclu√≠da com sucesso.")


        caminho_saida = "data/validated/clientes_validado.csv"
        os.makedirs(os.path.dirname(caminho_saida), exist_ok=True)
        df.to_csv(caminho_saida, index=False)
        logging.info(f"üìÅ Arquivo validado salvo em: {caminho_saida}")